service: janubx-datatransfers

frameworkVersion: ">=1.1.0 <2.0.0"

plugins:
  - serverless-python-requirements

package:
  exclude:
    - local/**
    - node_modules/**
    - .idea/**
    - .requirements/**
    - env/**
    - README.md
    - package.json
    - package-lock.json
    - requirements.txt

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  stage: dev
  environment:
    BASE_URL: {"Fn::Join": ["", ["https://", {"Ref": "ApiGatewayRestApi"}, ".execute-api.${self:provider.region}.amazonaws.com/${opt:stage, self:provider.stage}"]]}
    DYNAMODB_LSI: ${self:service}-${opt:stage, self:provider.stage}-lsi
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}-table
    SERVICE_VERSION: v1
    FUND_SERVICE_URL: {'Fn::ImportValue': NotesTableName}

functions:
  ping:
    handler: handler.ping
    events:
      - http:
          path: ping
          method: get
          cors: true
